### ISSUE TITLE
New GET /knowledge-graph/users/:id/projects

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#1038]
As a renku-graph API user, I'd like to be able to fetch info about all my projects, those already in KG as well as those which are not there, yet.

Acceptance criteria:
- [x] expose a new `GET /knowledge-graph/users/:id/projects` resource on the knowledge-graph service;
- [x] the `:id` has to be a valid user GitLab id (in the future we could allow emails, ORCIDs, etc.);
- [x] the resource to aggregate data from the TS and GitLab (the [user's projects](https://docs.gitlab.com/ee/api/projects.html#list-user-projects) resource);
- [x] user's projects here means all the projects the user is either a user or a member of (in the sense of GitLab which means the user is either a user of the project in GitLab or he/she is a member of that project);
- [x] in the absence of an access token, only public user's projects will be returned;
- [x] when an access token is given, all public, internal and private user's projects will be returned;
- [x] either OAuth or Private Access Token can be given for authentication and authorization;
- [x] the results will be sorted by name by default;
- [x] the response should be paged;
- [x] the response JSON will be of following shape:
  ```json
  [
    {
      "name": "name",
      "path": "group/subgroup/name",
      "visibility": "public",
      "date": "2012-11-15T10:00:00.000Z",
      "creator": "Jan Kowalski",
      "keywords": [
        "keyword1",
        "keyword2"
      ],
      "description": "desc",
      "_links": [
        {
          "rel": "details",
          "href": "http://t:5511/projects/group/subgroup/name"
        }
      ]
    },
    {
      "name": "name",
      "path": "group/subgroup/name",
      "visibility": "public",
      "date": "2012-11-15T10:00:00.000Z",
      "creator": "Jan Kowalski",
      "keywords": [
        "keyword1",
        "keyword2"
      ],
      "description": "desc",
      "_links": [
        {
          "rel": "activation",
          "href": "http://t:5511/projects/123/webhooks",
          "method": "POST"
        }
      ]
    }
  ]
  ```
- [x] for projects that are not in the KG yet, an `activation` link is returned instead of `details`;
- [x] when POSTing to the `activation` resource a relevant access token is mandatory;
- [x] return not activated projects only when `state=NOT_ACTIVATED` query param given;
- [x] return activated projects only when `state=ACTIVATED` query param given;
- [x] return all projects when no or `state=ALL` query param given;
- [x] update README/API docs;
- [x] add acceptance tests.

**Comment by andre-code** [comment]
Is it possible to accept an extra param to request only those that have the activation link?

**Comment by jachro** [comment]
@andre-code so maybe we can add an additional query parameter like `activated=true|false`?
