### ISSUE TITLE
The DS list returns information about the dataset project

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-graph#1059]
As a graph API user, I would like the DS list resource (GET /knowledge-graph/datasets) to return information about the first project in the dataset.

Acceptance criteria:

- [ ] GET /knowledge-graph/datasets to add the source project information of the dataset.
```
"project": {
    "name: "project name",
    "path": "project-path"
}
```

**Comment by jachro** [comment]
Not needed for now
