### ISSUE TITLE
Update link to docs

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-graph#1090]
Link to docs in repo's home page leads to 404:

![image](https://user-images.githubusercontent.com/16360283/190976896-ba2d388c-8a4b-470b-b83c-5e417dcd30e4.png)

**Comment by jachro** [comment]
Thanks Tasko. Honestly, I didn't even remember there's such a link on the Graph repo. Anyway, I fixed it. Depending on what you are looking for, a rather high-level view can be found there but for more in-depth info about the events flow, the repo's README should be more precise: https://github.com/SwissDataScienceCenter/renku-graph#event-flow. And, if you need anything in particular, I'm more than happy to help.
