### ISSUE TITLE
Provide a dataset search query

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-graph#117]
As an API user, I'd like to be able to search for datasets with the free text search. The matching data-sets should be having the given text occurring in the `name`, `authors` or `description`.

The endpoint:
`GET /knowledge-graph/datasets?query=<text>&sort=name|description|author:asc|desc`
where `query` is a mandatory parameter.

The result:
`OK` with the following JSON:
```
[
  {
    "identifier":"9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c",
    "name":"rmDaYfpehl",
    "description" : "vbnqyyjmbiBQpubavGpxlconuqj",  // optional property
    "published" : {
      "datePublished" : "2012-10-14T03:02:25.639Z", // optional property
      "creator" : [
        {
          "name" : "e wmtnxmcguz"
        },
        {
          "name" : "iilmadw vcxabmh",
          "email" : "ticUnrW@cBmrdomoa"             // optional property
        }
      ]
    },
    "projectsCount": 2, 
    "_links":[
      {
        "rel":"details",
        "href":"http://t:5511/datasets/9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c"
      }
    ]
  },
  {
    "identifier":"a1b1cb86-c664-4250-a1e3-578a8a22dcbb",
    "name":"a",
    "published" : {
      "datePublished" : "2010-10-14T03:02:25.639Z", // optional property
      "creator" : [
        {
          "name" : "e wmtnxmcguz"
        }
      ]
    },
    "projectsCount": 1, 
    "_links":[
      {
        "rel":"details",
        "href":"http://t:5511/datasets/a1b1cb86-c664-4250-a1e3-578a8a22dcbb"
      }
    ]
  }
]
```

Assumptions:
* description should be cut after 200 chars; after some re-thinking, I'm more into position to leave the trimming to the API user;
* the matching should work for substrings of words - this kind of searches may be achieved with wildcards: `?` for single character, `*` for multiple characters;
* ~do not search if the phrase is shorted than 3 chars;~
* it should be possible to do sorting by `name`, `datePublished`, `projectsCount`.

For more info on free text searches in Jena see https://jena.apache.org/documentation/query/text-query.html.

**Comment by jachro** [comment]
There's an issue #97 which introduces a GraphQL query for datasets searching. This query allows to look for single project's datasets and reduce the result to a list of `id` or/and `name`. This can be achieved with:
```
{
  "query": "{ 
    dataSets(projectPath: \"namespace/project\") {
      id name 
    } 
  }"
}
```
@vfried, @rokroskar how do you envision this search functionality?

**Comment by rokroskar** [comment]
I added some more information to the description - in SwissDataScienceCenter/renku-ui#521 @lorenzo-cavazzi also mentions a `usedBy` field which we should try to include if it's not too big of an effort (if it is, we should make a separate issue for that).

**Comment by jachro** [comment]
I moved the API definition here from [renku-ui#521](https://github.com/SwissDataScienceCenter/renku-ui/issues/521) as I imagine this is the issue for that work.

I assume it's going to be part of the GraphQL's `dataSets` resource so translating it from REST the query should look like this:
```
{
  "query": "{ 
    dataSets(project: String = "", // eg "namespace/project"
                     createdBy: String = "", // eg "user@host" - if we'd like to search by a 'username' only, an additional triple would need to be added) {
      id !String
      name(containing: String = "", sort: ASC|DESC) !String
      description(containing: String = "", sort: ASC|DESC) String
      createdBy(sort: ASC|DESC): !String // eg "user@host"
      usedIn: ![!String] // projects names
    } 
  }"
}

**Assumptions:**
* Currently, there's no information about preferred/starred data-sets, so there's no possibility to query or filter by these.
* Filtering by `name` or `description` can be achieved by passing a _contains_ phrase to relevant property. A simple _contains_ will be
* Sorting can be done by giving the `sort` argument to a relevant property.
* There's single `createdBy` property as that's the only info we have at the moment.
* There's no `stars` info associated with the data-set in the Triples Store so it cannot be provided.
* There's no data-set `visibility` available in the Triples Store so it's not possible to return that.

**Comment by vfried** [comment]
RESPONSE FROM THE SEARCH:
name
id
description (short description)
authors
date ?

**Comment by rokroskar** [comment]
Can this be closed @jachro?

**Comment by jachro** [comment]
Yes, that's done.
