### ISSUE TITLE
Sparql queries should match projects by the name triple

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#127]
Currently, lineage and data-sets related sparql queries find projects by matching the project resource. That's a bit brittle as the host part of the resource is different per environment and requires special `knowledge-graph.renku.url` config property. This should be changed and project matching should be done using the following triple:
```<project-resource> <schema:name> "namespace/project-name"```

As part of the story, the `knowledge-graph.renku.url` config value should be removed.

**Comment by rokroskar** [comment]
Actually the `knowledge-graph.renku.url` is redundant already because there is the `global.renku.domain` value which includes all the relevant information.

**Comment by rokroskar** [comment]
But this will be brittle too - what if the user changes the name of the project?

**Comment by jachro** [comment]
So:
* actually we've got a bug as it won't work with the current full URL matching too
* I assume one of the ways to solve is to act on the `project_rename` system hook and update the triples (https://docs.gitlab.com/ce/system_hooks/system_hooks.html)

**Comment by jachro** [comment]
Won't be done as we decided to deal with the issue in a way described here: https://github.com/SwissDataScienceCenter/renku-python/pull/701
