### ISSUE TITLE
Edit basic metadata from a dataset

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-graph#129]
As a KG API user, I'd like to be able to update data-set's `description` or `name`

The endpoint:
`POST /knowledge-graph/datasets/:id`

Payload:
```
{
  "name": "rmDaYfpehl",
  "description": "vbnqyyjmbiBQpubavGpxlconuqj"
}
```
Note: 
* `name` is a mandatory property and cannot be blank.
* `description` is optional but cannot be blank if specified.

Result:
* `OK` if all went fine
* `BAD_REQUEST` when no `name` or  blank `name` or `description`.

**Comment by jachro** [comment]
Will be solved by modifying project's metadata files.
