### ISSUE TITLE
Create a `users` resource

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#135]
As a Renku user, I should be able to uniquely identify Renku user/creator/agent with a valid, queryable URL resource on the knowledge-graph.

The resource:
GET /knowledge-graph/users/:id

Response:
* `NOT_FOUND` when no user with the given id exists in the KG;
* `OK` with the payload:
```
{
  "_links" : [
    {
      "rel" : "self",
      "href" : "https://zemdgsw:9540/users/:id"
    }
  ],
  "identifier": "<UUID>",
  "name": "user name",
  "email": "user@host", // Optional
  "sameAs": "<orcid-id>"  // Optional
}
```
Assumption: the `orcid-id` goes under the `sameAs` triple. If not, any other property reflecting the `orcid-id` will be used instead.

**Comment by ableuler** [comment]
Do we have to build this endpoint ourselves? Can this information not come from keycloak?

**Comment by jachro** [comment]
I guess we've got some info about a user in Keycloak but it's the same story as with the Projects, as pieces we've got in Keycloak, probably some in GitLab and all the other things in the KG. I believe having a single point of truth is very beneficial.
