### ISSUE TITLE
Change the knowledge-graph's RENKU_RESOURCES_URL env variable to point to renku

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#141]
As a Renku owner, I'd like the `knowledge-graph` service to create links in its project endpoints' response bodies pointing to `http(s)://renku-host/projects/...` instead of `http(s)://renku-host/knowledge-graph/projects/...`

**Comment by rokroskar** [comment]
@jachro I believe the URI should be `http(s)://renku-host/entities/projects`

**Comment by jachro** [comment]
Thanks for linking these two! I wasn't part of the discussion last week so wasn't aware of the agreement. Effectively, from the knowledge-graph service point of view, it's a simple config change as I think I'd like to keep the endpoints naming on the service as is.

**Comment by jachro** [comment]
I'm guessing this is not needed anymore.
