### ISSUE TITLE
Improve content of the READMEs going to dockerhub

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#1476]
Apparently, dockehub requires some improvements of our READMEs in order to give us the functionality we need.

Acceptance criteria:
- [x] improve content of KG READMEs so dockerhub people are happy with. Perhaps, there's someone in the team who knows a bit more what information we should put there.

**Comment by eikek** [comment]
I updated the readmes on docker-hub for all kg services with the same template. Example: https://hub.docker.com/r/renku/webhook-service

**Comment by jachro** [comment]
Should we maybe also do `renku/renku-jena`?

**Comment by eikek** [comment]
Oh... 🤦

**Comment by eikek** [comment]
Done. Thanks!! I had strange problems accessing the eventlog repositiory. Docker always gives me errors (404s). I can't access it to change the description 😦

**Comment by eikek** [comment]
Ok, it seems that this is the only repo that failed on firefox. Using chromium I now also see https://hub.docker.com/repository/docker/renku/event-log/
