### ISSUE TITLE
MEMBER_SYNC process to read access_level and persist it in TS

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#1490]
As a renku graph user, when I'd like to be able to see the data I own when I query various Graph APIs.

Acceptance criteria:
- [ ] the `MEMBER_SYNC` process to read the `access_level` property from the response of Project Members All API and persist it in the TS
  - [ ] A new entity to be created for each member of the Project in the Project graph

  ```
  ?memberId a renku:ProjectMember
  ?memberId renku:project projected
  ?memberId renku:person personId
  ?memberId renku:role 'owner'|'maintainer'|'reader'
  ```

  - [ ] Each time the process, a check if the Access Level stored in the TS and fetched from GL is the same and update it in case it's different
- [ ] There are also other processes like `ADD_MIN_PROJECT_INFO` and `TRIPLES_GENERATED` that reads the list of project members. Probably these should also add info about the Access Level.
  - [ ] Quite likely we'd need to add a new `ProjectMember` type which will replace the `Person` type in the `Project.member` property
    - [ ] the encoder would need to cope with the new type and encode the new `ProjectMember` entities and keep the `schema:member` unchanged

**Comment by eikek** [comment]
This has been incorporated into #1538
