### ISSUE TITLE
GET /datasets?query=<phrase> to allow paging

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#154]
As a Renku user, I'd like the `knowledge-graph/datasets` endpoint to allow paging the results.

Acceptance criteria:
* two new optional query parameters `per_page` and `page` are introduced for controlling the number of items on the page and the page number;
* if `per_page` and `page` parameters are given the results with the requested number of items from the given page are returned;
* if no `per_page` and `page` parameters are given, then the defaults of `per_page=20` and `page=1` are used;
* if the number of found items is less than the given `per_page`, a not full page is returned;
* if a non-existing page is requested, an empty result set is returned but with valid info in the pagination headers;
* if either `per_page` or `page` is a non-positive int value, a `BAD_REQUEST 400` is returned;
* there are several pagination headers returned in the response:

| Header | Description |
| ------- | ------------ |
| Total | The total number of items |
| Total-Pages | The total number of pages |
| Per-Page | The number of items per page |
| Page | The index of the current page (starting at 1) |
| Next-Page | The index of the next page |
| Prev-Page | The index of the previous page |

* there are link headers sent back with each
response. They have rel set to prev/next/first/last and contain the relevant
URL. These should be used instead of own generated URLs;
* if there's no previous page the `prev` page link is not present;
* if there's no next page the `next` page link is not present;
* the paging solution should be done in a way it can be easily re-used on other endpoints;
* as part of the issue the Renku documentation is updated with the above;

**Comment by ciyer** [comment]
Could you follow the GitLab API for handling pagination? We already have a component on the client that is aware of how GitLab handles pagination, and it would be nice if we just need one component for pagination everywhere.

  https://gitlab.cci.drexel.edu/help/api/README.md#pagination

**Comment by jachro** [comment]
Hi @ciyer. Yes, but can we go with few modifications :) ? So:
* let's swap `limit` query parameter to GitLab's `per_page`; `page` we already have;
* default to page 1 if `page` param not given;
* my biggest concern are the headers entries as I'd prefer to stick to HETEOAS which we already use in all the other our endpoints and put 
prev/next/first/last to the `_links` metadata property in the JSON response body;
* similarly for the paging metadata (the number of pages, items and so on), I'd be more than happy to return the data GitLab returns (`X-Total`, `X-Total-Pages`, `X-Per-Page`, `X-Page`,  `X-Next-Page`,  `X-Prev-Page`) and more or less stick to that naming but my thinking is that if it's in the properly named `_paging` context, it's simply more understandable (due to the namespace), more readable and so less confusing in general. The other thing is that according to RFC-6648, the "X-" prefix should be dropped in the metadata keys so I'm guessing GitLab could follow that rule sooner or later anyway.
What are your thoughts?
