### ISSUE TITLE
Re-provisioning process causes GET projects/:id/events/status to bounce around near completion

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#171]
Currently, the re-provisioning process deals with x number of outdated Commit Events at a time before it takes another chunk. That causes the `GET projects/:id/events/status` not to return real information about the number of Commit Events to process but simply bounces around being almost complete depending on whether the chunk has been almost processed or it was simply picked-up.

**Comment by rokroskar** [comment]
balance -> bounce? :)

**Comment by jachro** [comment]
This got irrelevant now as we changed the re-provisioning process to re-do the whole world at once.
