### ISSUE TITLE
triples-generator to update Person's properties on new values

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#176]
As a Renku user, I'd like my name and email get updated in the KG when I change my local git settings.

Acceptance criteria:
* when new Person `schema:name` or `schema:email` get returned from the triples generation process, triples-generator should update the old values rather than inserting new ones (which causes duplicates of `schema:name` or/and `schema:email` created for that Person);

**Comment by rokroskar** [comment]
Right... I guess that is the simplest solution to that problem.
