### ISSUE TITLE
Re-provisioning process deleting datasets linked to different projects

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#180]
Unfortunately, the re-provisioning process deletes datasets which are linked to other projects. The way it should deal with the datasets is:
* remove only dataset triples with `schema:isPartOf` pointing to a project via the Commit Activity's `schema:isPartOf`; of course that's in the context of a specific commit scheduled for deletion;
* run a special post-re-provisioning clean-up deletion, removing eventual orphan datasets (datasets with no schema:isPartOf left);

**Comment by rokroskar** [comment]
Right... this makes sense.
