### ISSUE TITLE
JsonLD serialization mechanism

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#187]
As a Renku owner, I'd like Scala code to have a mechanism of serializing objects to JsonLD.

Acceptance criteria:
* the library to be built on top of `circe`;
* a JsonLD type to be introduced;
* the JsonLD type to enforce `id` and `types` presence;
* an `asJsonLD` method to be available on data types requiring an instance of  special `JsonLDEncoder` implicitly;
* migrate all the places in Graph Services producing JsonLD object to use the new solution.

**Comment by rokroskar** [comment]
related to https://github.com/SwissDataScienceCenter/renku-python/issues/700
