### ISSUE TITLE
graph-services to add prov:wasDerivedFrom for forked projects

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#189]
As a Renku owner, I'd like graph-services to add `prov:wasDerivedFrom` triple (https://www.w3.org/TR/prov-o/#wasDerivedFrom) to the forked project's metadata in the KG.

Acceptance criteria:
* [x] base on a currently processed Commit Event's project, triples generator to fetch relevant info from both GitLab (`GitLab/api/v4/projects` the `forked_from_project` property) and the KG (the `forked-from-project` from the triple `<fork-project> prov:wasDerivedFrom <forked-from-project>`);
* [x] if the KG's `forked-from-project` equals GitLab's  `forked_from_project` do nothing;
* [x] if the two projects are different then delete the old `prov:wasDerivedFrom`, `creator` and `dateCreated`  and create new ones based on the info from GitLab (`forked_from_project`, `created_at` and `creator_id`); the `creator_id` should be linked from the existing entity in the KG, or a new Person entity needs to be created if there's no Person with the new creator's email;
* [x] if there's no `prov:wasDerivedFrom` triple in the KG but there's some fork info in GitLab, then create the triple as well as link `creator` (if relevant Person entity already exists or create the Person otherwise) and update the `dateCreated`;
* [x] if there's no fork info in GitLab but there's a `prov:wasDerivedFrom` triple in the KG then remove the `prov:wasDerivedFrom` triple and link `creator` (if relevant Person entity exists or create the Person otherwise) and `dateCreated` using info from GitLab (`created_at` and `creator_id`);
* [x] if there are no forks on both sides do nothing;
* [ ] ~while the number of curation triples grows it would be nice to introduce some batching while sending the updates based on the triples to the KG.~

**Comment by rokroskar** [comment]
Does the fork event register for the project or is it a system-level event?

**Comment by jachro** [comment]
I'm not so sure, I have to try to do some set-up and simply check. The worst case scenario would be to listen to the `project_create` system hook and then call the [forks API](https://docs.gitlab.com/ee/api/projects.html#list-forks-of-a-project).
