### ISSUE TITLE
Create OpenAPI Json

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#199]
As a Renku user, I'd like to be able to see graph-services API documentation.

Acceptance criteria:
- [x] Create a model based on the OpenAPI Specification
- [ ] Include security schemes (see below)
- [ ] Serve the JSON at /knowledge-graph/spec.json
- [ ] Add the link to the Json [here](https://github.com/SwissDataScienceCenter/renku/blob/23dde6ba6e24d2ac66685f203f211aef32fa3287/helm-chart/renku/templates/swagger.yaml#L29-L30)

```json
    "securitySchemes": {
      "gitlab-token": {
        "in": "header",
        "name": "Authorization",
        "type": "apiKey"
      },
      "jwt": {
        "in": "header",
        "name": "Renku-User",
        "type": "apiKey"
      },
      "oidc": {
        "openIdConnectUrl": "/auth/realms/Renku/.well-known/openid-configuration",
        "type": "openIdConnect"
      }
    },
  "security": [
    {
      "oidc": []
    },
    {
      "JWT": [],
      "gitlab-token": []
    }
  ]
```

**Comment by travissarles** [comment]
Check to see if there's a plugin for http4s

**Comment by travissarles** [comment]
See Routes.scala in graph-commons for an example of the version endpoint. Add another subpackage similar to version. In the MicroservicesRoutes we append swagger routes.

**Comment by travissarles** [comment]
Create Swagger Json file in resources directory for each service

**Comment by travissarles** [comment]
Expose KG endpoints to main Renku swagger
