### ISSUE TITLE
Prototype the Graph Service

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-graph#2]
- [x] Get example/test metadata, most likely from an example project, with `renku log`. See also: #3, https://github.com/SwissDataScienceCenter/renku-python/issues/293
Example can be obtained as: https://gist.github.com/leafty/7d6135389aff201add35c4ad956620b6
- [ ] Sketch relevant entities, how they map to graphql objects and to JG objects. Of course, the entities also need to conform to the Renku ontology (https://github.com/SwissDataScienceCenter/renku-ontology/pull/5).
- [ ] Prototype graphql service, with static data. JG as a store backend is not required at this point.

**Comment by rokroskar** [comment]
closing -- has been superseded by other issues in https://github.com/orgs/SwissDataScienceCenter/projects/29
