### ISSUE TITLE
Replace Doobie with Skunk

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#219]
As a Renku owner, I'd like Graph Services to use Skunk instead of Doobie for accessing Postgres DB.

Acceptance criteria:
* Replace dependency to Doobie with Skunk and perform all the necessary changes so everything works as before;
* new issue - Use Skunk's notify functionality in the Events Processing flow;
* new issue - Use Skunk's notify functionality for the Metrics;
* new issue - Create an issue for creating a WebSocket version of the endpoint providing info about the processing status;

**Comment by joke1196** [comment]
- [ ] Add table which have a timestamp to the timestampzone adder migration
- [ ] verify that all #$ string interpolation in SQL queries cannot be transformed into a proper encoder type
- [ ] check all TODOs 
- [ ] Create compound encoders and decoders everywhere possible possible
