### ISSUE TITLE
JsonLD lib for Scala

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#229]
JsonLD is the base data representation used in Renku. As there's no enough feature-rich and reliable library for Scala at the moment, there's a need to create one for Renku.

**Comment by jachro** [comment]
Do not need an epic for these issues

**Comment by rokroskar** [comment]
Any chance to make this a separate package and make it ready for public consumption? i.e. add documentation and other supporting infrastructure

**Comment by jachro** [comment]
It would be nice to do that. I'll create an issue for that.
