### ISSUE TITLE
Graph Services to work with modified datasets

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#240]
As a Renku user, I'd like Graph Services to be able to work with modified datasets according to the changes done to the dataset modelling in renku-python (926 Differentiate imported and modified dataset from its origin).

Acceptance criteria:  
* entities generators present in Graph Services have to generate new dataset entities in case of a change of a dataset (replace `schema:sameAs` with `prov:wasDerivedFrom`, remove the `schema:url`, update the `schema:dateCreated` and `schema:creator`);
* the free-text dataset search query to combine the found dataset, its ancestors and descendants;
* the dataset by identifier search query to combine the found dataset, its ancestors and descendants;

**Comment by rokroskar** [comment]
Can we have a sketch of the KG for this? There are a few questions to answer. For example - what is the dataset id used for? Is it used to uniquely identify the dataset? If so, then the id needs to take into account the commit/revision and we need a new ID for every commit. On the other hand, the id could point to the dataset entity and there could be several versions of that entity. Those might be blank nodes, without a unique id or they might have an id derived from the original id.

**Comment by jachro** [comment]
I guess it's a bit cleaner now once we nailed down the dataset modification flow as described in https://github.com/SwissDataScienceCenter/renku-python/issues/926.

I still have some doubts about the modified datasets and their presence in the results of either the free-text search query or the dataset by id search. My thinking is that if a dataset got modified thoroughly and it's only derived from some ds, should it still be put into one bag together with datasets which are identical to the found ds? Wouldn't be maybe better to add some new properties to the results named like `derivedFrom` and `sourceTo`?

**Comment by jachro** [comment]
Duplicate of #306
