### ISSUE TITLE
dataset KG information is incorrect in forked projects

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-graph#243]
# Description

1. Create a dataset D in project P
2. Fork project P to get project P'
3. Add data to dataset D in project P'

This data now appears in the dataset in project P, even though it is not there.

![image](https://user-images.githubusercontent.com/1196411/73749330-747a7580-475b-11ea-81a4-f1e238a740af.png)

You can see this here: https://dev.renku.ch/projects/cramakridemo/test-dataset-add/datasets/d70da756-7d56-4a2d-9f2f-5a6cbbc20bee/
The first file, `43_bf_3c8d8dedbd7296f3dd4b37934a6d210bb83da1375ab3310e9fac2cfc97fb` is not in this dataset, but it is in the fork.

**Comment by rokroskar** [comment]
This is related to https://github.com/SwissDataScienceCenter/renku-python/issues/926
