### ISSUE TITLE
Migrate renku-graph to GitHub Actions

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#251]
As a Renku owner, I'd like renku-graph services to be built using GitHub Actions.

Acceptance Criteria:
* create a workflow to run `sbt release` on an auto-branches (one for a tag and one for a new snapshot);
* create/reuse a workflow to merge auto-branches mentioned above;
* create/reuse a workflow to bump the version of graph services in `Renku` repository;
* decommission old Travis jobs;

closes #463

**Comment by travissarles** [comment]
Note to self: Ask @Panaetius for advice
