### ISSUE TITLE
Spike: find out if we can secure our KG with ACLs

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#260]
As a Renku user, I don't want metadata of my or my organisation private/internal projects to be queryable by users not having access to them.

Acceptance criteria:
* find out if Jena's ACLs allow achieving the non-queryable goal in a presence of user's token or credentials when running a query;

A start point can be this: https://jena.apache.org/documentation/fuseki2/data-access-control

**Comment by jachro** [comment]
The spike findings:
* It looks like the standard Jena way of doing data security is to define users access rights per graph. Effectively, what you do is you define which user(s) can access which graph(s). The main problem with the approach from our perspective is that you configure the access rights in a config file which is read during Fuseki start so it's not very dynamic and cannot be changed once the server is started. More details can be found here: https://jena.apache.org/documentation/fuseki2/data-access-control#graph-acl
* Next step: https://jena.apache.org/documentation/permissions/example.html

**Comment by rokroskar** [comment]
is the answer yes? or 42? 🤖

**Comment by jachro** [comment]
We decided a non-Jena specific option would work better for us. So we ended up with the service level verification based on  the GitLab and Triples Store members.
