### ISSUE TITLE
Made the renku-graph services to use the Event Log service instead of the lib

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#270]
As a Renku owner, I'd like all the Event Log API interactions in all the renku-graph modules to be done through the REST API not by using the lib.

Acceptance criteria:
- [x] find usages of the Event Log lib in the renku-graph modules and replace them with the relevant calls to the event-log service REST APIs;
- [x] refactor event-log service;
- [x] refactor the `events_waiting_count` metric so it's incremented and decremented by API calls rather than backed by DB queries;
* - [x] rename `db-event-log` to `event-log`;
* - [x] think of adding relevant links to the endpoints responses;
* - [x] rename command classes and method names and put them into proper packages;
* - [x] take out project dependency to event-log from webhook-service and triples-generator;
* - [x] clean-up webhook-service and triples-generator helm charts (remove unused env variables);
* - [x] get rid of event-log DB transactors in webhook-service and triples-generator;
* - [x] check for eventual TODOs;
- [ ] ~raise an issue for Gateway to call event-log service to find processing status;~
- [ ] ~raise an issue for webhook-service to remove the processing status;~

**Comment by rokroskar** [comment]
Would this open the door for <gasp> triggering a re-indexing?

**Comment by jachro** [comment]
Yes, it'd be possible. In what circumstances would you like to do that?
