### ISSUE TITLE
GET /knowledge-graph/projects/:namespace/:name/datasets response enrichment

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#298]
As a Renku Graph API user, I'd like the `GET /knowledge-graph/projects/:namespace/:name/datasets` to respond with the same information as the `GET /knowledge-graph/datasets`.

**Acceptance criteria:**
* the project's datasets endpoint to return the following structure for each dataset:
```json
   {  
      "identifier": "9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c",
      "name":"rmDaYfpehl",
      "sameAs": "http://host/url1",
      "description": "vbnqyyjmbiBQpubavGpxlconuqj",  // optional property
      "published": {
        "datePublished": "2012-10-14T03:02:25.639Z", // optional property
        "creator": [
          {
            "name": "e wmtnxmcguz"
          },
          {
            "name": "iilmadw vcxabmh",
            "email": "ticUnrW@cBmrdomoa"             // optional property
          }
        ]
      },
      "projectsCount": 2,
      "_links":[  
         {  
            "rel":"details",
            "href":"http://t:5511/datasets/9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c"
         }
      ]
   }
```

**Comment by vfried** [comment]
@jachro i just read the description and it looks good to me. Do we have a "last edited" date or something similar?

**Comment by jachro** [comment]
Not so sure if we can give any modification dates. I'd have to sync with Mohammad to check how dataset immutability deals with that.

**Comment by vfried** [comment]
I think for now it's ok... i can imagine in the future we might want this but for now what you mentioned is good.
