### ISSUE TITLE
POST /knowledge-graph/query

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#300]
As a Renku Graph maintainer, I'd like to have a resource on the KG that allows me to send a SPARQL query to be executed on the RDF store. At the moment, dealing with issues related to data in the KG is pretty difficult and time-consuming.

**Acceptance criteria:**
* a new `POST /knowledge-graph/queries` endpoint to be added to KG microservice;
* the endpoint to accept `JSON` payloads of the following structure:
```json
{
  "name": "my query name", // non-blank, 35 characters max
  "query": "some query"
}
```
* the endpoint to return `BAD_REQUEST (400)` when given request body is invalid;
* the endpoint to return `BAD_REQUEST (400)` when the given query is not valid;
* the endpoint to return `UNAUTHORIZED (401)` there's no `Authorization: Bearer <gitlab-user-token>` header or the token is invalid;
* the endpoint to return `OK (200)` with the query results in the body as `JSON` when the given payload is valid and query executes successfully,

**Examples:**
* query with specified fields:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?agent
WHERE {
  ?commit rdf:type prov:Activity;
          prov:agent ?agent.
  ?agent rdf:type prov:SoftwareAgent.
}
```
Response:
```
[{
  "agent": "<https://github.com/swissdatasciencecenter/renku-python/tree/v0.10.3>"
}]
```
* query without specified fields:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT *
WHERE {
  ?commit rdf:type prov:Activity;
          prov:agent ?agent.
  ?agent rdf:type prov:SoftwareAgent.
}
```
Response:
```
[{
  "commit": "<https://dev.renku.ch/activities/commit/00069a5c708e0e4a46e2e537d2d2d0e3392c2bdb>",
  "agent": "<https://github.com/swissdatasciencecenter/renku-python/tree/v0.10.3>"
}]
```

----

This issue may require some tweaks but generally might be a good starting point for the resource once [the user Triples Store](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2160001025/Sending+graph+data+to+third+party+storage) concept has materialised.

**Comment by rokroskar** [comment]
This would be a really good idea - what about authentication? The gateway could handle that I suppose? cc @ableuler

**Comment by ableuler** [comment]
> This would be a really good idea - what about authentication? The gateway could handle that I suppose? cc @ableuler

The gateway could handle authentication easily if you don't mind getting your Renku session cookie from your browser after login. But that's probably falling into the "difficult and time-consuming" category too...?

This endpoint would be for development and debugging purposes only, right? Would you apply some logic/checks to the query before executing it? Otherwise I'm wondering what added benefit of this service would be over querying Jena directly.

**Comment by rokroskar** [comment]
I had in mind something like logging in via the browser and then getting the gateway to give you a token that you could use on the command line, like the JWT - then you would use the `Authentication: Bearer <token>` header on the request. 

@jachro why wouldn't this endpoint just proxy the request to the sparql endpoint? What's the use of `name` in the JSON payload?

**Comment by jachro** [comment]
First of all many thanks for your comments. Let me try to bring over the idea of how I'd imagine Jena security could work. So I'd like that all the KG endpoints will require some GitLab Access Token to be passed in the Bearer so KG will pass it to Jena and then Jena internally will be able to use it to find what projects this token is authorised to. That's more or less the outcome of [the spike on Jena's ADT](https://github.com/SwissDataScienceCenter/renku-graph/issues/260).

The idea behind the `name` is to force users of the API to give some query name/id so we can track the performance of their queries and flag up eventual problems here.

**Comment by rokroskar** [comment]
> So I'd like that all the KG endpoints will require some GitLab Access Token to be passed in the Bearer so KG will pass it to Jena and then Jena internally will be able to use it to find what projects this token is authorised to.

So what I have in mind is that the client would use something generic like the JWT from keycloak in the request to the endpoint and then the gateway could swap it for whatever token is appropriate. The reason I'm bringing this up is because we could use a similar mechanism for other clients, e.g. the renku CLI.

**Comment by rokroskar** [comment]
@ableuler we don't want the sparql endpoint to be exposed to the world at this stage.

**Comment by jachro** [comment]
@ableuler I guess we don't until the mechanism of swapping JWT to Access Token is not in place. What I can do for now is simply force users to present some fixed Bearer to prevent anyone be able to run (and eventually kill) our Jena :)

**Comment by ableuler** [comment]
> @ableuler we don't want the sparql endpoint to be exposed to the world at this stage.

But how is exposing the SPARQL endpoint through the gateway different from exposing some service that allows you to execute any SPARQL query on Jena?

**Comment by jachro** [comment]
I updated the issue with the agreement we reached today.

**Comment by jachro** [comment]
I think we are not ready to implement that now or even in the near future
