### ISSUE TITLE
KG dataset resources to work with immutable datasets

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#306]
As a Renku API user, I'd like KG dataset resources to show the latest versions of datasets if they are modified.

**Acceptance criteria:**
* `GET /knowledge-graph/datasets` to look for matches of the given criteria only among the latest datasets versions; the latest version of a dataset is understood as one without other datasets having the `prov:wasDerivedFrom` pointing to it;
* `GET /knowledge-graph/datasets/:id` to return details of the dataset with the given `identifier`; it's acceptable that if the given `id` is not the `id` of the latest version of the dataset, details of that particular version will be returned;
* `GET /knowledge-graph/projects/:namespace/:name/datasets` to return all project's datasets in the versions the project uses them; that does not necessarily mean the datasets need to be in the latest version exists as for instance, certain datasets could have newer versions on the projects where they were originally created;
* for the `GET /knowledge-graph/datasets/:id` and `GET /knowledge-graph/projects/:namespace/:name/datasets`:
  * the `sameAs` property:
    * will be present if it's set explicitly on the dataset (a case when a dataset was imported and not modified in the project);
    * will be present even if it's not set explicitly on the dataset (a case when a dataset was modified in the project); its value will be a reference to this dataset's `id`;
  * additional `derivedFrom` property will be added when the dataset has some previous version(s) (it's a modified dataset); the value of the property will be a reference to the previous version of the dataset (its `id`);
  * additional `projectIdentifier` property will be added showing dataset identifier within a project (mapped from `https://swissdatasciencecenter.github.io/renku-ontology#identifier`);
    * the `projectIdentifier` value does not change for a dataset within a project and when the dataset is modified it holds its value;
    * the `projectIdentifier` value gets a new value when a dataset is imported to another project;
    * multiple datasets can have the same `projectIdentifier` value only if there was a dataset on some project and that project got forked.

**Things to consider:**
* does the insertion of additional aggregate triples make sense?
  * potentially useful aggregates: `topmostSameAs` and `topmostWasDerivedFrom`;
  * problem of several events being processed at once;
  * problem of events not being processed in order;
    * the aggregate preparation would have to update not only the current dataset details but also all the datasets which were imported from it (and all their descendants);
  * problem of updating the aggregates for other projects;

**Comment by ciyer** [comment]
I think it makes sense that you generally want to see the latest version of a dataset, so, overall, I think this is the right idea. What I do not understand, though, is how you find older versions of a dataset if you want to see them. Do you need to recursively traverse the wasDerivedFrom field, or will there eventually be a query for this?

**Comment by mohammad-sdsc** [comment]
> GET /knowledge-graph/datasets to look for matches of the given criteria only among the latest datasets versions; the latest version of a dataset is understood as one without other datasets having the prov:wasDerivedFrom pointing to it;

I believe we should also consider projects in this query. For example, if a project using a dataset which sits at the middle of this `prov:wasDrivedFrom` chain (with no subsequent modification in that project), we should be still able to see that dataset.

**Comment by jachro** [comment]
Thanks @ciyer 

So for the older dataset versions, I had an idea that in the response of `GET /knowledge-graph/datasets/:id` there will be another property potentially in the following shape: 
```json
{
...
  "versions": [
    {
      "identifier": "a1b1cb86-c664-4250-a1e3-578a8a22dcbb",
      "published": {
        "datePublished": "2012-10-14T03:02:25.639Z",
        "creator": [
          {
            "name": "iilmadw vcxabmh",
            "email": "ticUnrW@cBmrdomoa"
          }
        ]
      },
      "_links": [
        {
          "rel": "details",
          "href": "http://t:5511/datasets/a1b1cb86-c664-4250-a1e3-578a8a22dcbb"
        }
      ]
    }
  ]
...
}
```

But I'm not aiming to address that in this issue.

**Comment by jachro** [comment]
@mohammad-sdsc that's a good point. I'll add it to the acceptance criteria. However, I'm guessing it's more about the `GET /knowledge-graph/projects/:namespace/:name/datasets` rather than the `GET /knowledge-graph/datasets` as this is purely for searching through datasets data, I mean this search does not assume the datasets are linked to any projects. Is that what you were thinking about?

**Comment by mohammad-sdsc** [comment]
Depends on the search result we want to return: If we want to return all projects that contain a dataset then we need to include it; otherwise, it won't be needed for this endpoint.

**Comment by jachro** [comment]
I have to say it's going a bit tricky here again. The `GET /knowledge-graph/datasets` response does not tell what projects use the datasets matching the criteria. However, it gives info about the number of projects each of the found datasets is used in. My thinking is that if we look for matches among the latest versions of datasets, we should say how many projects use that matched version of the dataset. I believe such an approach makes things a bit less complicated and potentially easier for people to understand.

From the other side, I do agree that the project's datasets resource should be showing all the datasets it uses, including the exact versions of the datasets, not the latest ones.
