### ISSUE TITLE
triples-generator to dynamically adjust the load

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#309]
As a Renku owner, I'd like TG instance to adjust the number of events it processes dynamically depending on the available resources.

**Acceptance criteria:**
* reword the TG's `generation-processes-number` to `max-generation-processes-number` (the service code and its charts);
* TG to decide whether to accept next event for processing or not by looking at:
  * current number of triples generation processes <= the `max-generation-processes-number` ;
  * average memory usage from the last 10sec (or some other horizon if that more appropriate) <= 95%;
  * average CPU usage from the last 10sec (or some other horizon if that more appropriate) <= 95%;
  * average time of currently running triples generation processes <= 10mins;
  * some other metrics.

All the limits should be treated as proposals.

As an alternative, an approach where there's a governing service managing number of running TGs instances should be evaluated. However, it seems reasonable that each TG can adjust its own load by looking at its own resources while the governing service can be built on top of that. All that should probably be addressed in a separate issue.

**Comment by rokroskar** [comment]
This should probably be used together with https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by jachro** [comment]
It looks like the high load on TG is not a problem anymore (at least for now)
