### ISSUE TITLE
Lineage endpoint to work with workflow info storing changes

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#313]
As a renku-graph API user, I'd like the `POST /knowledge-graph/graphql` (lineage resource) to work in the presence of the changes done to the way workflow info is stored (check [here](https://github.com/SwissDataScienceCenter/renku-python/pull/1185) for more details).

Acceptance criteria:
* update the entities in renku-graph to fit the new modelling;
* the lineage resource served by the knowledge-graph's GraphQL endpoint (`POST /knowledge-graph/graphql`) to work as before the workflow info storing changes;
* are there more things to adjust???

**Comment by rokroskar** [comment]
An open question is how we want to represent `rerun` and `update` which result in the creation of `Workflow` nodes - @ciyer has been looking at this and can maybe provide some feedback on the preferred response? The current implementation allows us more flexibility in how we query and represent the workflows and their subprocesses.

**Comment by jachro** [comment]
I agree we can and should change that but I'm not entirely sure if that should be addressed in this issue. Personally, I'd prefer to add it [here](https://github.com/SwissDataScienceCenter/renku-graph/issues/92).

**Comment by rokroskar** [comment]
True, if the scope of this issue is to just allow for the current functionality with the new KG model then that's fine.
