### ISSUE TITLE
Simplify sparql query results binding

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-graph#331]
As a Renku Graph developer, I'd like mapping the query results could be done in less verbose way.

**Acceptance criteria:**
- [ ] come up with some tooling for decoding query results rows so instead of `cursor.downField("results").downField("bindings").as(decodeList(rowDecoder))` maybe something like:
  - [ ] `cursor.binding.one` when a single object is expected;
  - [ ] `cursor.binding.option` in case there could be one or no object returned;
  - [ ] `cursor.binding.list` in case there could be a list of objects returned;
- [ ] come up with some tooling so mapping properties values instead of `cursor.downField("projectId").downField("value").as[ResourceId]` could be done at least with something like `cursor.downField("projectId").valueAs[ResourceId]`;
- [ ] pay attention to the usefulness of the tooling and try to mimic API from other libraries (potentially doobie) if possible and it makes sense so it's easier to reason and adopt the new solution;
- [ ] refactor all the classes extending `IORdfStoreClient`.

**Comment by jachro** [comment]
Closing at it was done as part of some other issue few months ago.
