### ISSUE TITLE
Clean up the Generation model outgoing links

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-graph#332]
The Generation entity possesses a property called prov:activity which points to any Activity entity. This property can be removed, as the model handle this property as a reverse from the Activity entity.

Acceptance criterias: 

  * The serialization of Generation should not contain a link to an Activity
  * The serialization of Activity should contain a `@reverse`  link to a Generation 
  * The lineage tests exemplar data should still represent correctly the link between Generation and Activity

**Comment by jachro** [comment]
Not relevant
