### ISSUE TITLE
Event-log fails when querying the data

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#354]
It looks that probably due to some updates (maybe doobie) event-log starts to fail when querying the data.
```
2020-08-13 15:40:31,690 ERROR application - Finding events to process failed
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.time.Instant. Use setObject() with an explicit Types value to specify the type to use.
```
This particular error happened on an environment created by a CI job but I believe it can be reproduced when deploying renku-graph `1.6.2` on any env.

### Reproduction steps

1. Deploy Renku with graph version 1.6.2 to a dev environment 
2.  in the renku project, go to charts/renku/requirements.yaml
3. In a project, add a dataset 

It would be great if we could make the test verifying the failing query (Finding events to process) to fail, too.

It could worth checking if maybe some other queries in the event-log and maybe projects-tokens service are not affected by the change.

Hint: these two could be relevant:
* https://github.com/tpolecat/doobie/issues/1095
* https://github.com/tpolecat/doobie/releases
Maybe we can simply extend the event-log's `TypesSerializers` with relevant traits so it becomes `trait TypesSerializers extends TimeMetaInstances with SqlMeta with MetaConstructors`?

**Comment by travissarles** [comment]
TODO: talk to david about this. Requires new version of environment

**Comment by travissarles** [comment]
The error message originates here:
https://github.com/SwissDataScienceCenter/renku-graph/blob/master/event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDispatcher.scala#L70

The type error comes from the EventFetcherImpl class which uses `java.util.time.Instant` here: 
https://github.com/SwissDataScienceCenter/renku-graph/blob/master/event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala#L53

The method which I believe contains the SQL for Postgres is here: 
thttps://github.com/SwissDataScienceCenter/renku-graph/blob/master/event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala#L53

I will try to see what SQL gets generated and if that doesn't work, try to get Postgres to log the incoming queries

**Comment by travissarles** [comment]
Importing implicits from many places doesn't seem to help. I've added 
`scalacOptions ++= Seq("-Xlog-implicits")
`
to event-log/build.sbt to see how the implicits are getting resolved. I didn't see any conversion happening for the Instant. As discussed previously, Scala seems to be calling toString on Instant before any implicit conversion can happen. 

I tried to force the conversion like so:

`import package doobie.`enum`.JdbcType.TimeSteamp
val timeNow: TimeStamp = now()`

But it couldn't find the import. for some reason.

**Comment by travissarles** [comment]
I wrote a test here: https://github.com/SwissDataScienceCenter/renku-graph/pull/359/files

The problem seems to be fine in the **EventPersister** class but it's still problematic in **EventFetcher** where we're seeing issues in the logs.
