### ISSUE TITLE
Triples Store re-provisioning to recreate the dataset

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#361]
As a Renku Graph maintainer, I'd like the dataset in the Triples Store to be recreated during the re-provisioning process.

Acceptance criteria:
* check if Jena API allows to delete the whole renku dataset;
* if dataset deletion is possible replace the dataset clearing step with dataset recreation;

**Comment by travissarles** [comment]
Previously, Kuba was experiencing issues while trying to delete all of the data in a dataset where there were some corrupted triples which didn't contain a subject. Triples without subjects couldn't be deleted so the dataset wasn't empty. 

```
DELETE {?s ?p ?o}
WHERE {?s ?p ?o}
```

@joke1196 and I found that you can use the `s-put` fuseki cli command to put an empty turtle file (i.e. a file with no triples). 

```
s-put  http://localhost:3030/ds1/data default ~/Downloads/empty.ttl
```

We tried to insert triples with missing subjects into Jena running in Docker on my MacBook but were unsuccessful.  We decided we needed to use the dev data which had corrupted triples. Kuba uploaded the large Jena directory from Dev to David's K8s environment for testing. This included the database file.

**Comment by travissarles** [comment]
We will try the approach which s-put uses to upload an empty turtle file.

**Comment by travissarles** [comment]
The approach of pushing an empty turtle file caused a crash in Jena
