### ISSUE TITLE
Update libs and sbt plugins

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#395]
As a renku-graph owner, I'd like all the libs to be on the latest versions.

**Acceptance criteria:**
* update scala (1.12.x);
* update all the libs;
* update sbt;
* update all the plugins;
* create a similar issue for the next release :)

**Comment by travissarles** [comment]
What's the advantage of updating to Java 12 if it doesn't have long-term support like Java 11? https://en.wikipedia.org/wiki/Java_version_history

**Comment by jachro** [comment]
Sorry, I meant `scala` :)

**Comment by jachro** [comment]
closed by #410
