### ISSUE TITLE
Make the jena chart a dependency of the graph

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-graph#41]
We want to be able to *not* deploy Jena (e.g. in a dev environment). 

- [ ] move the Jena chart to its own repo
- [ ] make Jena a conditional dependency (add it to `requirements.yaml`). See e.g. https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/requirements.yaml#L17

**Comment by jachro** [comment]
@rokroskar do we still want to do that?

**Comment by rokroskar** [comment]
I think it would be nice - and we should contribute the Jena chart to the community somehow

**Comment by jachro** [comment]
Done
