### ISSUE TITLE
event-log's PATCH /events/:event-id/:project-id to accept events' JSON-LD payloads

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#422]
As a renku-graph maintainer, I'd like event-log service's `PATCH /events/:event-id/:project-id` to accept events with the event's payload.

### Current design
- Triples Generator currently uses `renku log` to get JSON-LD 
- Triples generator curates payload calls this method once it has finished processing

### Proposed implementation
- `TG` calls Renku Core requesting triples. 
- `TG` gets a 200 response and then send an event `GENERATING_TRIPLES` to `EL`
- `TG` starts to generate triples using `renku log` command;  
- `TG` sends JSON-LD payload and status `TRIPLES GENERATED` back to `EL` when the triples generation is finihes;
- `EL` sends it back to `TG` with `TRIPLES_GENERATED` status and `TG` curates event and sends to JENA
- `TG` sends `TRIPLES_STORE` status back to `EL`

![el-tg-core.png](https://images.zenhubusercontent.com/5f27d663e844ed0bc7c12c63/e56bce82-2feb-490d-80d6-1c60f07e2c82)

**Acceptance criteria:** (each major point corresponds to a separate PR)
- [x] *migration:* `PROCESSING` status to `GENERATING_TRIPLES`
  - [x] create a DB migration on EL startup which changes `PROCESSING` to `GENERATING_TRIPLES`
- [x] new `GENERATING_TRIPLES`, `TRIPLES_GENERATED` and `TRANSFORMING_TRIPLES` statuses to be added to the event-log;  Note: we will still have the `PROCESSING` status temporarily to ease transition unprocessed.
  - [x] assure the `GET /metrics` endpoint to work with the new statuses;
    - [x] adapt the `events_statuses_count` to work with all the new statues; ideally, the metrics mechanisms are changed in a way they don't have to be addapted when there are changes to the statuses in the future);
    - [x] adapt the `events_awaiting_generation_count`; counting events with the `NEW`, `RECOVERABLE_FAILURE` statuses (check if we count events in `` status for more than the `MaxProcessingTime`);
    - [x] adapt the `events_under_triples_generation_count`; counting events with the `GENERATING_TRIPLES` status;
    - [x] adapt the `events_awaiting_transformation_count`;   counting events with the `TRIPLES_GENERATED` status
    - [x] introduce a `events_under_transformation_count`; counting events with the `TRANSFORMING_TRIPLES` status;
    - [x] update the relevant dashboards;
  - [x] assure the `GET /processing-status?project-id=:id` to work with the new statuses; all the new statuses to be classified as in progress states;
- [x] change `unprocessed` subscription category so the status gets changed to `GENERATING_TRIPLES`
- [x] the `PATCH /events/:event-id/:project-id` endpoint to accept status transition from `GENERATING_TRIPLES` to `TRIPLES_GENERATED`;
  - [x] validation and behaviour of the endpoint after receiving following payload should be similar to current transition from `PROCESSING` to `NEW`;
- [x] modify behaviour of the `PATCH /events/:event-id/:project-id` endpoint when requested to transition status to the `TRIPLES_STORE`;
  - [x] the endpoint to return `200 (Ok)` if the status is `TRANSFORMING_TRIPLES` (or `GENERATING_TRIPLES` - needed temporarily in the transition phase to the Core generating triples);
  - [x] `409 (Conflict)` to be returned in any other case;
- [x] modify behaviour of the `PATCH /events/:event-id/:project-id` endpoint when requested to transition status to failure statues;
  - [x] the endpoint to return `200 (Ok)` only if the status is `GENERATING_TRIPLES` or `TRANSFORMING_TRIPLES`;
  - [x] `409 (Conflict)` to be returned in any other case;
  - [x] migrate `RECOVERABLE_FAILURE` to `GENERATION_RECOVERABLE_FAILURE`
  - [x] migrate `NON_RECOVERABLE_FAILURE` to `GENERATION_NON_RECOVERABLE_FAILURE`
  - [x] add two new failure status `TRANSFORMATION_NON_RECOVERABLE_FAILURE` and `TRANSFORMATION_RECOVERABLE_FAILURE` 
- [x] a new `event_payload` table with an `event_id`, `project`, and `payload` columns to be added to the `event_log` DB;
- [x] the `PATCH /events/:event-id/:project-id` endpoint to accept following events;
  ```json
  {
    "status": "TRIPLES_GENERATED",
    "payload": "json-ld as string",
  }
  ```
  - [x] if any of the given properties is missing or has blank value, `404 (BAD_REQUEST)` should be returned;
  - [x] if the request is valid but there's no event with the given `event-id` and `project-id`, `404 (Not Found)` should be returned;
  - [x] if the request is valid and event with the given `event-id` and `project-id` exists but has status different than `GENERATING_TRIPLES`, `409 (Conflict)` should be returned;
  - [x] if the request is valid and event with the given `event-id` and `project-id` exists and has status `GENERATING_TRIPLES`, the `event_payload` table should be updated/inserted with the `payload` value, the `schema_version`. The `status` column in the events table to be updated with `TRIPLES_GENERATED` and `200 (Ok)` should be returned;
- [x] update event-log's `README.md` with the info about the changes to the endpoint;

**Comment by travissarles** [comment]
[https://app.zenhub.com/files/147648238/280abeb9-a30e-45e1-b02c-a0ca9829c787/download](https://app.zenhub.com/files/147648238/280abeb9-a30e-45e1-b02c-a0ca9829c787/download)
