### ISSUE TITLE
Transformation process to add project's members

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#433]
As a renku-graph maintainer, I'd like the triples curation process to enrich the project metadata by adding the project's members.

**Acceptance criteria:**
- [ ] ~consider using ontology described [here](https://www.w3.org/wiki/WebAccessControl); (this looks like it will make things (incl. queries) much more complicated) maybe not necessary~
- [x] create a `subscription_category_sync_times` table in the event-log DB;
- [x] add a new subscription category for project members synchronisation;
- [x] add `categoryName` property to the events sent by event-log;
- [ ] create a process on TG to synchronise single projects members;
  - [x] the process to fetch project members from GitLab;
  - [x] the process to find existing members in TS; upsert members which have changed or are newly added (try to find a person by GitLabId and link it to the Project if it exists); unlink members not existing in GitLab as this project members;
- [x] change the `POST /events` endpoint on the TG to accept `members_sync` events and direct these events to the member sync process;
- [ ] make TG to subscribe for the `members_sync` events on the EL;

![projects-members-sync](https://user-images.githubusercontent.com/1461762/103760896-11056180-5016-11eb-900d-6e733c91199e.png)

[projects-members-sync.drawio.txt](https://github.com/SwissDataScienceCenter/renku-graph/files/5775431/projects-members-sync.drawio.txt)

![member-sync](https://user-images.githubusercontent.com/1461762/104593462-08450900-5670-11eb-8a91-df88e36d93ef.png)

**Comment by rokroskar** [comment]
When adding additional elements to the graph model, we should make sure that this is documented and consistent with the SHACL shapes defined for the KG as a whole.

**Comment by jachro** [comment]
Good point. Although I think that could force us to open our SHACL as e.g. project members could not appear on payloads generated by `renku log`.

**Comment by rokroskar** [comment]
What do you mean by "open"? To not enforce shapes? I think a closed shape can still have optional elements. Could be wrong though - @Panaetius will know :)
