### ISSUE TITLE
knowledge-graph endpoints queries to use the projects members data to filter out data

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#436]
As a renku-graph user, I'd like data of my private/internal projects to be visible to members of my projects (as defined in GitLab).

**Acceptance criteria:**
- [ ] find out the order of endpoints to secure;
- [ ] update all the knowledge-graph endpoints queries so they present data from projects the caller is authorised to;
  - [ ] the endpoints to return 404 when the user has no rights to see a project;
  - [ ] make sure the queries return data from all the public projects regardless of the Access Token the caller passed or not;
  - [ ] make sure the queries return data from all the non-public projects where the user is listed as a member;
  - [ ] make sure the queries do not return data from all the non-public projects where the user is not listed as a member; 
- [ ] make sure Renku Core is going to us through Gateway before securing `/projects`, `/projects/datasets` and `/datasets/:id` endpoints;
- [ ] endpoint specific requirements:
  - [ ] `/projects` to filter out forks the user has no access to;

**Comment by rokroskar** [comment]
Isn't https://github.com/SwissDataScienceCenter/renku-gateway/issues/300 also blocking this?

**Comment by jachro** [comment]
Not really, as the endpoints will still work showing the public project's data if you don't show an access token. They will eventually start showing more data once there's a valid token passed to them.
