### ISSUE TITLE
webhook-service to opt-in all existing private/internal renku projects

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#437]
As a Renku user, I'd like all my already existing non-public projects to be automatically opted-in to KG.

**Acceptance criteria:**
- [ ] introduce a new batch job on the webhook-service opting-in all existing non-public projects;
  - [ ] the job to run once on the service start-up;
  - [ ] the job to ask Gateway for access tokens of all the users (probably a new API needed on Gateway);
  - [ ] the job to use the access tokens to fetch all the [user projects](https://docs.gitlab.com/ee/api/projects.html#list-user-projects);
  - [ ] the job to check which projects are missing in the event-log, create a hook on them and kick off the process of loading the whole commits history;

**Comment by rokroskar** [comment]
Not sure sure that this is a good approach - what happens if I have an instance of Renku connected to a generic public gitlab? I probably don't want _all_ of my projects in renku, but just the ones that I have used within Renku.

**Comment by rokroskar** [comment]
Oh I also just noticed that it's automatic opt-in for all private projects - I would say this definitely should _not_ be the case.

**Comment by jachro** [comment]
I believe opting-in could happen only for renku repositories (potentially those having `.renku` folder).

I'm just thinking about other alternatives we've got. Do you think we should keep the opting-in mechanism even after we secure data in the KG? What would be the benefit of securing it, then?

**Comment by rokroskar** [comment]
I'm conflicted, tbh - maybe if it's limited to renku projects it's fine but still, if the user initially made a renku project and opted out of the KG we shouldn't then automatically include their project in the KG without giving the option to stay out of they want.

**Comment by jachro** [comment]
Hm, good point, I'm not sure what we should do for these. However, if we leave these projects out of KG then we'll never be able to use KG to free-text search for a project.

**Comment by jachro** [comment]
This won't be done.
