### ISSUE TITLE
Event-log gets restarted

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#444]
It looks there's some memory leakage which causes EL to restart.

Notice that the memory usage is gradually going up:
<img width="1006" alt="Screen Shot 2020-10-07 at 11 15 17" src="https://user-images.githubusercontent.com/11528695/95312003-ac0f6380-088e-11eb-9290-82cb04c7dcc0.png">

Hypothesis: Subscribers are getting freed up but there are too many of the objects which are freeing them. Each request has a thread. We fixed the thread pool. Cats IO creates fibers, which are a lightweight version of a thread. Looking at number of threads, all will always be used.

Instead we could just store the time when a subscriber should be freed up. Create a process which goes through subscribers to check for free ones.

**Comment by rokroskar** [comment]
Can you look at the historical log for the deployment and see if this is indeed the case?
