### ISSUE TITLE
Change authorization header for oauth case

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-graph#46]
Instead of `OAUTH-TOKEN: '<some-gitlab-user-token>` i would suggest 
`AUTHORIZATION: 'Bearer <some-gitlab-user-token>'` for the headers (following the gitlab API).

**Comment by rokroskar** [comment]
Isn't `Bearer` used specifically for JWT?

**Comment by ableuler** [comment]
Nope (https://oauth.net/2/bearer-tokens/)
