### ISSUE TITLE
Working with JSON-LD entities is difficult and brittle

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#525]
As a renku-graph owner, I'm happy with the way JSON-LD entities are modelled however using them seems to be pretty difficult and the tests using them brittle.

**The problem**
The fact is that the current entities modelling in Renku is pretty complex. The model is reflected on the graph side and it seems to be built in a robust and almost compile-time safe manner, however, the sticking points between the model and the code using it seems to be a bit difficult to maintain and understand. What's even worse, is that the tests using the model are a bit brittle due to translation from the models used in the tests and the JSON-LD model. It seems reasonable that there are sets of implicit/non-implicit JSON-LD objects required to instantiate more complex JSON-LD structures and so it would be required that the tests would provide translations from its domain models to relevant entities objects.

**Acceptance criteria:**
* asses if the idea of having JSON-LD entities requiring other entities (implicitly or explicitly depending on a case) makes sense; probably the place which would require the most changes would be `bundles` object which methods take long lists of arguments with defaults; that arguments would have to be changed to entity objects rather than entity objects's properties; for instance, the `bunldes#nonModifiedDataSetCommit` could be taking a `DataSet` object explicitly and `Project` and `Activity` implicitly;
* change all the usages of the `bundles` so no entities' properties are passed to them but entity objects; provide relevant translations from certain domain models to entities models.

**Comment by joke1196** [comment]
Done as part of #667
