### ISSUE TITLE
Code stats gathering tool

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#589]
As a renku-graph maintainer, I'd like graph services code is evaluated so various stats can be provided to the developers.

**The problem**
Actually, there's no problem as such :) It would be simply nice to have some stats about the code so we could tweak things here and there.

**Acceptance criteria:**
- [x] try if there's an easy way of integrating SonarQube into our CI pipeline;
- [x] try if using https://stryker-mutator.io/ would work for us;
- [x] if not SonarQube maybe at least scoverage could be less problematic;

- [ ] Try out compiler options

**Comment by travissarles** [comment]
- SonarQube doesn't have good support for Scala. It's about two years out of date
- stryker-mutator is more modern but doesn't seem to provide useful feedback

**Comment by travissarles** [comment]
- Check out possible code coverage tool  if it seems like coverage could be useful https://diamantidis.github.io/2020/05/17/ci-with-github-actions-for-scala-project
