### ISSUE TITLE
Spike an idea of managing new service instances from within another service

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#590]
As a renku-graph maintainer, I'd like to verify if it would be possible to spin new instances of service of choice from within another service.

**The problem**
Going through the next steps towards the _No downtime re-provisioning_, an idea of managing instances of some service from another service. Without going into many details this issue is simply to check how feasible is that.

**Acceptance criteria:**
- [ ] ~talk to RP team to find out how far they are from supporting `renku log` for different schema versions;~
- [ ] try out the [kubernetes client for scala](https://github.com/joan38/kubernetes-client) to:
  - [ ] create a new instance of some service; it's mandatory to be able to pass environment variables to the new instance;
  - [ ] remove an instance of a service;
  - [ ] evaluate what info the managing service would have to have in order to perform the above operations (hopefully no admin credentials are needed);
- [ ] check if we can achieve all the goals above with kubernetes REST API;
- [ ] check how we can use kubernetes jobs instead of services:
  - [ ] a crazy idea: would it be possible that the job (as described [here as the Queue with Variable Pod Count](https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/)) is started by TG and:
    * the job itself subscribes for the awaiting generation events with capacity 1 directly in EL;
    * performs the tg generation upon event arrival and sends back the payload;
    * dies? if yes, then we'd need to remove this subscriber from the EL before dying; if not, maybe it can live and die when no events for more than x mins? It would still need to remove itself from the EL registry;
    * what would we gain by dying the log job after processing a single event? more k8s complaint? leave k8s free hand for scaling up/down? wouldn't that be that k8s would still have the possibility to create/destroy instances if e.g. all running instance are busy working?
    * how TG would know whether to create more instances or not? Should the decision be taken only on TG start-up (and some parallelism set to some value depending on whether there's re-provisioning going on; in such a case the parallelism would be spread across both log jobs)?
    * is it true that the job(s) would need to be monitored by TG which would eventually spin them up if they died (using the same logic as on TG start-up)?
  - [ ] things to check:
    - [ ] how to re-create the job once it succeeded? doing `kubectl -n kuba apply -f k8s/job.yaml` returns `job.batch/pi unchanged`;
    - [ ] should maybe the job be of the `parallel` type (potentially with a shorter timeout before succeeding for re-provisioning job); what if there are no events for the current provisioning job for more than the timeout and all of them terminate? would new ones get created upon the arrival of new events? it would be a bit nasty if TG needs to keep an eye on the job and re-create it if all pods succeeded and died... according to [this](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup) that's probably the case;
    - [ ] the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically) says TG should probably clean up the succeeded jobs; or perhaps we could set `ttlSecondsAfterFinished: 100`;

[an example yaml tg-job.yaml.txt](https://github.com/SwissDataScienceCenter/renku-graph/files/6110429/tg-job.yaml.txt)
A command to deploy the job: `kubectl -n kuba apply -f tg-job.yaml`
A command to show the job status: `kubectl -n kuba describe jobs/tg`

**Comment by rokroskar** [comment]
> use kubernetes jobs instead of services

This is a great idea imho! If you wanted to offload some of the error-handling functionality you could also look into a kubernetes workflow system like [argo](https://argoproj.github.io/).

**Comment by jachro** [comment]
Yes, we're pretty excited about that :)
