### ISSUE TITLE
GET /knowledge-graph/datasets/:id to not return the `isPartOf` property

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#631]
As a renku-graph API user, I don't want to receive the `isPartOf` property from the `GET /knowledge-graph/datasets/:id` resource as it's confusing in the presence of the `project` and `usedIn`.

**The problem**
Once #630 is done, there's a redundant and confusing `isPartOf` property returned by the resource.

**Acceptance criteria:**
- [ ] the resource not to return the `isPartOf` property.

**Comment by travissarles** [comment]
Closed by PR 731
