### ISSUE TITLE
TG to create jobs of the commit-graph-generator type

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#642]
**Acceptance criteria:**
- [ ] TG to use the k8s API to create job of the commit-graph-generator type;
  - [ ] use [the Queue with Variable Pod Count](https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/) as an example;
  - [ ] find out a proper value for the `parallelism` property
  - [ ] check how k8s manages the job containers; how it creates new ones, deletes when there are no resources;
  - [ ] find out how to plug prometheus into a job (probably we'd need to hook the metrics into the EL)

An example job spec: [https://app.zenhub.com/files/147648238/7eacd9bf-7cfa-40e5-89d0-dc37ffc30a8e/download](https://app.zenhub.com/files/147648238/7eacd9bf-7cfa-40e5-89d0-dc37ffc30a8e/download)
A command to deploy the job: `kubectl -n renku-ci-gr-645 apply -f cgg.yaml`
A command to show the job status: `kubectl -n renku-ci-gr-645 describe jobs/commit-graph-generator`

An example job spec:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: commit-graph-generator
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 4
  parallelism: 30
  template:
    spec:
      containers:
      - name: commit-graph-generator-job
        image: renku/commit-graph-generator:1.33.2-n006.h67d68a0c
        env:
        - name: SCHEMA_VERSION
          value: "8"
        - name: EVENT_LOG_BASE_URL
          value: http://renku-ci-gr-645-event-log:9005
        - name: TOKEN_REPOSITORY_BASE_URL
          value: http://renku-ci-gr-645-token-repository:9003
        - name: GITLAB_BASE_URL
          value: https://dev.renku.ch/gitlab
        - name: GITLAB_RATE_LIMIT
          value: 30/sec```

**Comment by travissarles** [comment]
[https://app.zenhub.com/files/147648238/32daf5f6-5a02-4822-a8fd-d217510ffc88/download](https://app.zenhub.com/files/147648238/32daf5f6-5a02-4822-a8fd-d217510ffc88/download)
