### ISSUE TITLE
Change the re-provisioning process

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#660]
Prerequisites:
- [x] try out the new renku graph generation functionality:
  - [x] how does this work for repos having commit(s) that fails generation, e.g. there are 3 commits on a repo, the first and the last one are fine for graph generation but the 2nd fails; when we do graph generation after the 3rd commit, we should get graph for the commits before the 2nd one (the failing one); this is to prove that running `generate graph` on all the commits produces the same result as running it on the very last commit only;
  - [x] to work out the sequence of steps to use the new graph generation in TG, e.g. Renku migrate -> check if the graph generation was already done on the repo (to look at some JSON file somewhere in the .renku) -> Renku graph generate
  
  * I took the new `renku graph` functionality for a test drive on few projects. It worked well on small projects as well as on big ones like `covid-19-public-data`. The order of operations TG to follow should be like this:
    * `renku migrate`
    * `renku graph generate`; if the process exists with `0` or `1` and the `Error: Graph metadata exists. Use ``--force`` to regenerate it.` message, all is good; otherwise, things went wrong;
    * `renku graph export` returns the JSON-LD;

**Acceptance criteria:**
- [x] keeping in mind that the new graph generation does not include info about files that are not involved in datasets or workflows, clean-up code which generates such objects (maybe smth in the bundles?);
- [x] make sure the `TRIPLES_GENERATED` category finder does issue events only for the latest events in status `TRIPLES_GENERATED` which have a payload;
- [x] add a new `EVENTS_STATUS_CHANGE` consume event category which should:
  - [x] be changing statuses for the given event as well as all the events older than the given one to `TRIPLES_GENERATED`; events in status `SKIPPED` should not be touched;
  - [x] event could be changing status (depending on the data in the event) for: ~all the events (to `NEW`), for all the project events (to `NEW`),~ for all the project events older than given event id (to `TRIPLES_GENERATED` or `TRIPLES_STORE`)
  - [x] When changing status to `NEW` remove payload and processing time
  - [x] `AWAITING_DELETION` event should be removed 
  - [x] should we migrate the _all events to `NEW`_ status change to the new event type?
    - [x] switch TG to the new event
    - [x] clean-up the old endpoint doing the same task
- [x] change the steps in the triples generation flow to accommodate the new Renku graph generation process (see prerequisites);
~- [ ] add a new row to the `compatibility-matrix` to kick-off re-provisioning process on the next deployment;~
~- [ ] create a new `RE_PROVISIONING` subscription category on EL which issues a single event for each project (a relevant row needs to be added to the `subscription_category_sync_time` table for each project); the finder should start from the most recent projects and take the latest (non `SKIPPED`) event for each project;~
~- [ ] create a corresponding `RE_PROVISIONING` event consuming category on TG which should be very similar to the current `AWAITING_GENERATION` flow (except the `RE_PROVISIONING` should be forcing the graph generation);~
- [x] change the `AWAITING_GENERATION` category finder to issue the latest event for a project;
- [x] change the current re-provisioning process on TG so it:
  - [x] truncates Jena;
  - [x] tells EL to change all event status to `NEW`;
~- [ ] EL should issue `EVENT_STATUS_CHANGE` when there is a call to the event status change endpoint only for `TRIPLES_GENERATED` and `TRIPLES_STORE` ~
- [x] EL `EVENT_STATUS_CHANGE` should change the status of the event in the payload to the newStatus in the payload
  - [x] The payload should be inserted as well as the processingTime
- [x] TG should send a `EVENT_STATUS_CHANGE` event when an event is either turned to `TRIPLES_GENERATED` or `TRIPLES_STORE`
- [x] Verify event with which status is changed on the global change status endpoint (we should not change the `SKIPPED` event) 
- [x] Verify statistics query for event status (this maybe should be grouped by project (~one status by project)) 
- [x] Clean up change status endpoint
  - [x] Add handler for all status change on  `EVENTS_STATUS_CHANGE` event consumer
  - [x] Remove status change patch endpoint
- [x] think of a way to verify the data coming from the CLI;
  - [x] provide translation from the `testentities` to entities' encoders
  - [x] add test to all the entities decoders
  - [x] add validation to the model
  - [x] change the transformation processes
  - [x] take out the `triples: JsonLDTriples` from the `CuratedTriples` class
  - [x] verify if we'll be able to decode single values when there's a single value in an array
  - [x] read additional project info (e.g. template) from Json-LD payload
  - [x] check with the CLI team if the assumption for the project template info modelling/decoding is correct, e.g. is that ok to expect all the template fields to be present and not to decode the `TemplateInfo` object even if one of them is missing (obviously, the fewer options there the better for us); the initial attempt of modelling the Template Info can be found in [this patch](https://github.com/SwissDataScienceCenter/renku-graph/files/6956127/project_template_info_support.patch.zip)
  - [x] check with the CLI team if the `renku:automatedTemplateUpdate` (or other template info fields) might get a different value; if yes, the transformation process we'd need to read the current KG value and generate a delete query if different;
  - [x] encode project namespace so it gets into triples store
  - [x] add the GroupedRun entity (and any other that are missing) - create a new issue
  - [x] renku:Run to renku:Plan
- [x] merge with master
- [x] add acceptance test for the re-provisioninng process
  - [x] test how things work for all kinds of input/output params including streams - potentially the acceptance test would need to create a workflow which does e.g. `renku run echo a >> file.txt` and another which would read from a stream and verify if things work through the lineage endpoint; such test should even work on the old model so if the test passes we should be able to merge it to renku/master;
  - [x] try to find out if it's possible to test the re-provisioning process on the renku-graph acceptance-tests level; probably the tests would need to restart the TG with some different valuse for the `compatibility-matrix`, wait for the re-provisioning process and see if things get rebuilt;
- [x] could we try not to break the API? Only hasPart.name and datecreated on the DatasetProject could cause an issue. Verify with UI team. If not, create an issue for the UI.
  - [x] Maybe return entity.location instead of name?

**Comment by joke1196** [comment]
Looking into constraints validation at the graph level: 
- https://www.stardog.com/blog/data-quality-with-icv/

**Comment by joke1196** [comment]
Acceptance test issue was created for a better test of renku run workflow: https://github.com/SwissDataScienceCenter/renku/issues/2234
