### ISSUE TITLE
Releases done with conventional commits

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#664]
Elevate the "naked" tags to actual releases, including release notes (which can be assembled automatically through [conventional changelog](https://github.com/conventional-changelog/conventional-changelog)), and info about things to watch out for (like database migrations, necessary chart value changes, etc)

**Comment by travissarles** [comment]
Look at UI or Renku Python is doing this

**Comment by travissarles** [comment]
How to use `compile-changelog` https://github.com/SwissDataScienceCenter/sdsc-dev-docs/tree/master/renku-release#compile-changelog
