### ISSUE TITLE
Evaluate if Stardog can be a Jena replacement

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#681]
Try to go through the points described [here](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/741572611/Triplestore+Evaluation+2020) to see if Stardog can be Jena replacement.

**Comment by joke1196** [comment]
After the presentation on the 26th of November, we will need to look into the license of Stardog to be absolutely sure what we can or cannot use.
