### ISSUE TITLE
KG to expose a new lineage endpoint

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#695]
As a renku-graph owner, I'd the lineage endpoint to be exposed as a REST endpoint.

**The problem**
Currently, lineage is served via the graphql endpoint. However, the way it's used doesn't require graphql (our clients always fetch all the fields).

**Acceptance criteria:**
- [x] add a new `GET knowledge-graph/project/:id/resource/:path/lineage`;
- [x] make sure there's authentication and authorization on the endpoint;
- [ ] let the UI and Oksana know about the new endpoint and ask them to switch to it;
- [x] update KG's README.md
- [x] create a follow up issue that:
  - [x] removes the graphql endpoint + does a clean-up (sangria to be dropped);
  - [x] update the lineage query so there's no project members filtering;

**Comment by travissarles** [comment]
See KG Endpoint.scala
