### ISSUE TITLE
Reorganize graph acceptance test stub

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-graph#737]
With the complexity of the code base growing it is more and more difficult to think of everything to stub in the acceptance test. A good start would be to have only one way to setup a stub like gitlab. This stub would mock the whole API with all its endpoints. 
This way we would have better consistency. 

This means revamping the tests, for example we would gather all the information, Project, Commits, Committer beforehand and provide all this information to one function that would stub the whole API

**Comment by jachro** [comment]
Done as part of #660
