### ISSUE TITLE
Process and store Activity annotation

### ISSUE THREAD

**Issue by vigsterkr** [SwissDataScienceCenter/renku-graph#793]
Renku supports through plugins annotations to an `Activity`. this basically allows one to extend the `Activity` with some custom semantics, and as a result expand the knowledge graph of the project.

These `Annotations` should be stored as well in the KG.

an example project: https://renkulab.io/projects/vigsterkr/renku-mls-demo 

----

Support for Annotation will be probably introduced together with the user Triples Store instances (described [here](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2160001025/Sending+graph+data+to+third+party+storage))

**Comment by jachro** [comment]
Needs some more thinking.
