### ISSUE TITLE
Write a reflection about model changes

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-graph#800]
In Confluence write a reflection about model changes:

- [ ] What went well
- [ ] What are the advantages of the new model
- [ ] What side projects came out of the changes (i.e. creating a Scala version of the model in test and for production)
- [ ] What helped coordination between KG and RP teams
- [ ] What we could do next time to make the process easier

**Comment by jachro** [comment]
We probably don't need an issue for that.
