### ISSUE TITLE
Write a short blog post about the current work

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-graph#801]
In order to share what we've been doing in a more digestible manner, it could be helpful to write a short blog post every sprint about the work we've accomplished. This could include: 

- [ ] Before/after Screenshots of Grafana graphs showing improvements in memory, cpu, performance, etc. 
- [ ] A few words about the benefits to users
- [ ] Links to documents describing ongoing issues (e.g. model changes)
- [ ] Ideas we'd like to explore further (e.g. triplestore replacement)

- [ ] Duplicate this issue for the upcoming sprint

**Comment by jachro** [comment]
Probably
