### ISSUE TITLE
Webhook creation should return 201 

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-graph#81]
When creating new webhook through a POST request, we currently get the HTTP code 200 (ok) instead of 201 (created).

**Comment by jachro** [comment]
It was a requirement to return OK (200) when you try to create a hook which is already there and CREATED (201) when the hook creation happened. You should be also getting some meaningful response bodies: `{"message": "Hook already existed"}` and `{"message": "Hook created"}` respectively.
