### ISSUE TITLE
Upgrade to JDK 18

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#836]
As a renku graph maintainer, I'd like graph services to run on JDK 18.

**The reason**
JDK 18 seems to offer much better GC algorithms.

Acceptance criteria:
- [ ] upgrade images of all graph services
- [ ] upgrade image in the renku acceptance-tests

**Comment by travissarles** [comment]
Change JDK on local machine and do an `sbt clean test`
