### ISSUE TITLE
Prefer to use ClusterIP renku-gitlab, where possible

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku-graph#85]
this is likely to be a cheap a change, the intention is to allow easily dependencies of this format:
* `renku-gitlab | Hostname | my-renku-gitlab.domain.ch `
* `renku-postgresql | Hostname | my-renku-db.domain.ch `

**Comment by rokroskar** [comment]
Why is this issue in the `renku-graph` repo?

**Comment by jachro** [comment]
I think the benefit would be that even if Gateway is down, the Graph Services would work as normal without even noticing that. The other thing is that there seem to be some unnecessary network hops which also produce some more load on our services.
@fgeorgatos anything more?

**Comment by fgeorgatos** [comment]
indeed, let's reduce the extra dependencies where not strictly required; 
also, if we prefer native k8s paths, we stand to benefit from greater k8s ecosystems options.

**Comment by rokroskar** [comment]
Sorry I don't follow - what is the proposal here exactly? What is CIP?

**Comment by fgeorgatos** [comment]
ok, i renamed in the title CIP to ClusterIP, I come to realise `cip` is not as standard k8s terminology as I thought it is. 

topic t.b.d. tomorrow

**Comment by rokroskar** [comment]
you mean to use the kubernetes DNS name instead of the public hostname?

**Comment by fgeorgatos** [comment]
correct. 

When there is choice, I perceive this as the preferred approach, since it is k8s-native and bypasses the other layers (notably ssl & ingress).

**Comment by rokroskar** [comment]
yes sure, if there is no browser involved the services should not talk over public host names but use the internal ones instead. I was under the impression that it was the case here but maybe not @jachro?

**Comment by ableuler** [comment]
I disagree. I think gitlab should be reached through its publicly reachable hostname per default. Using the k8s service name for this will make the difference between our "standard" deployment and deployments which rely on external gitlab instances bigger and thus harder to maintain.

**Comment by jachro** [comment]
I believe we should not play that issue as we lean towards treating GitLab as an external dependency.
