### ISSUE TITLE
return more metadata with the lineage query

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-graph#92]
The lineage query should return metadata about the nodes and edges - which data maps to which inputs/outputs as well as node types (code/process vs. data).

**Acceptance criteria:**
* revise if that's still relevant: https://github.com/SwissDataScienceCenter/renku-graph/issues/267

**Comment by rokroskar** [comment]
Is the information needed for this in the KG already or does it need work on the graph-production end?

**Comment by jachro** [comment]
So would the requirement translate into:
* for every node we need a node type [Code|Process|Data];
* additional edges between Data nodes (representing inputs and outputs) and Process nodes should put on;

I added that just to present my understanding (or misunderstanding) of the issue :)

**Comment by jachro** [comment]
The issue was created back in 2019. Closing as it doesn't even have anything precise.
