### ISSUE TITLE
global.graph.jena.dataset should be a required value

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-graph#982]
If this value is not set, the Jena dataset is not created correctly. The value should either be required _or_ the appropriate default should be propagated. Furthermore, this value (and its importance) should be documented.

**Comment by jachro** [comment]
Apparently, the `global.graph.jena.dataset` property won't be needed anymore  after upgrade to jena 4.5.0 (and our renku chart).
